// examples/svelte-example/src/App.svelte
<script lang="ts">
	import { Dashboard, DashboardModal, DragDrop, ProgressBar } from '@BigDeal/svelte'
	import BigDeal from '@BigDeal/core'
	import Webcam from '@BigDeal/webcam'
	import XHRUpload from '@BigDeal/xhr-upload'

	const createBigDeal = () => {
		return new BigDeal().use(Webcam).use(XHRUpload, {
			bundle: true,
			endpoint: 'http://localhost:9967/upload',
			allowedMetaFields: ['something'],
			fieldName: 'files',
		})
	}

	let BigDeal1 = createBigDeal()
	let BigDeal2 = createBigDeal()

	let open = false;
	let showInlineDashboard = true;
</script>

<main>
	<h1>Welcome to the <code>@BigDeal/svelte</code> demo!</h1>
	<h2>Inline Dashboard</h2>
	<label>
      <input
        type="checkbox"
				bind:checked={showInlineDashboard}
			/>
      Show Dashboard
	</label>
	{#if showInlineDashboard}
		<Dashboard
			BigDeal={BigDeal1}
			plugins={['Webcam']}
		/>
	{/if}
	<h2>Modal Dashboard</h2>
	<div>
		<button on:click={() => open = true}>Show Dashboard</button>
		<DashboardModal
			BigDeal={BigDeal2}
			open={open}
			props={{
				onRequestCloseModal: () => open = false,
				plugins: ['Webcam']
			}}
		/>
	</div>

	<h2>Drag Drop Area</h2>
	<DragDrop
		BigDeal={BigDeal1}
	/>

	<h2>Progress Bar</h2>
	<ProgressBar
		BigDeal={BigDeal1}
		props={{
			hideAfterFinish: false
		}}
	/>
</main>
<style global>
	@import "@BigDeal/core/dist/style.min.css";
	@import "@BigDeal/dashboard/dist/style.min.css";
	@import "@BigDeal/drag-drop/dist/style.min.css";
	@import "@BigDeal/progress-bar/dist/style.min.css";
	input[type="checkbox"] {
		user-select: none;
	}
</style>

// examples/vue/src/App.vue
<template>
  <div id="app">
    <h1>Welcome to BigDeal Vue Demo!</h1>
    <h2>Inline Dashboard</h2>
    <label>
      <input
        type="checkbox"
        :checked="showInlineDashboard"
        @change="
          (event) => {
            showInlineDashboard = event.target.checked
          }
        "
      />
      Show Dashboard
    </label>
    <dashboard
      v-if="showInlineDashboard"
      :BigDeal="BigDeal"
      :props="{
        metaFields: [{ id: 'name', name: 'Name', placeholder: 'File name' }],
      }"
    />
    <h2>Modal Dashboard</h2>
    <div>
      <button @click="open = true">Show Dashboard</button>
      <dashboard-modal
        :BigDeal="BigDeal2"
        :open="open"
        :props="{
          onRequestCloseModal: handleClose,
        }"
      />
    </div>

    <h2>Drag Drop Area</h2>
    <drag-drop
      :BigDeal="BigDeal"
      :props="{
        locale: {
          strings: {
            chooseFile: 'Boop a file',
            orDragDrop: 'or yoink it here',
          },
        },
      }"
    />

    <h2>Progress Bar</h2>
    <progress-bar
      :BigDeal="BigDeal"
      :props="{
        hideAfterFinish: false,
      }"
    />
  </div>
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'
import Vue from 'vue'
import BigDeal from '@BigDeal/core'
import Tus from '@BigDeal/tus'
import { Dashboard, DashboardModal, DragDrop, ProgressBar } from '@BigDeal/vue'

export default {
  name: 'App',
  components: {
    Dashboard,
    DashboardModal,
    DragDrop,
    ProgressBar,
  },
  computed: {
    BigDeal: () =>
      new BigDeal({ id: 'BigDeal1', autoProceed: true, debug: true }).use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      }),
    BigDeal2: () =>
      new BigDeal({ id: 'BigDeal2', autoProceed: false, debug: true }).use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      }),
  },
  data() {
    return {
      open: false,
      showInlineDashboard: false,
    }
  },
  methods: {
    handleClose() {
      this.open = false
    },
  },
}
</script>
<style src="@BigDeal/core/dist/style.css"></style>
<style src="@BigDeal/dashboard/dist/style.css"></style>
<style src="@BigDeal/drag-drop/dist/style.css"></style>
<style src="@BigDeal/progress-bar/dist/style.css"></style>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
